### PR TITLE
Physical fitness

### PR DESCRIPTION
**Pull request by Manoj-kumar-surabhi**
## Type of Change
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Checklist before requesting a review
- [x] I have followed the git practices outlined [here](GitPractices.md) to ensure code conflicts are minimized
- [x] My code follows the style guidelines of this project outlined [here](UIGuidelines.md)
- [x] I have performed a self-review of my code. It runs without errors and follows the [Best Coding Practices](BestCodingPractices.md)
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] There are no API keys, passwords, usernames, or other secrets in the code. .env files are used for these secrets.
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by Divy0409 — CHANGES_REQUESTED** [review]
Unfortunately we can not merge your branch as it is having some conflicts. Solve those conflicts. Moreover, please update your Pull Request description..

**Comment by jeffreywallphd** [comment]
@Manoj-kumar-surabhi you can ignore the conflicts in the /dist folder and in the package-lock.json file. Those are in the .gitignore. You should focus on the conflicts in src/App.jsx.

**Comment by Manoj-kumar-surabhi** [comment]
Instead of using a NavLink, I used a hyperlink to redirect to the physical fitness website. Now this change has been undone, and NavLink has been added back in app.jsx.

**Comment by kbaker49** [comment]
Im not sure what all your uses are for the images but we should not have individual logos for each part of our application, so I would suggest removing those. In addition, we are using Font Awesome symbols across the app so if you were using those images for symbols, please refer to font awesome.

**Review by kbaker49 — COMMENTED** [review]
Not sure what some of this stuff in the footer.tsx file is? the paragraph on line 55? If you could please also separate out your inline styling and css files that would be great. Some things have inline styles and something are being styled from other files.

**Comment by jeffreywallphd** [comment]
Also, please make sure that you add all of your images into the "Images" folder that @kbaker49 recently created. For the images to populate to the build properly, you also need to make sure you have them imported within your jsx files on the pages where they are used. Please see the logo import in App.jsx for an example.

**Comment by jeffreywallphd** [comment]
@Manoj-kumar-surabhi please take a look at the comments in this pull request thread. I am going to close this pull request without merging, because there is too much work for the reviewers to do in one sitting. What I would advise is that you create a new branch (ex. physical_fitness2) and slowly begin integrating content from the physical_fitness branch into the physical_fitness2 branch. Don't wait to integrate everything in the new branch before pushing and making a pull request. Please make multiple pull requests as you transition your content to the new branch.

**Pull request closed without merging**
