### PR TITLE
new packages and physical fitness folder in svr

### PR DESCRIPTION
**Pull request by Manoj-kumar-surabhi**
## Describe your changes
- Added new packages to both dependencies and devDependencies.
- Created a new folder named "physical_fitness" in the `svr` directory.
- Moved `physical_fitness.tsx` to the `view` directory as per instructions.

## List the team you are on
- Physical Fitness

## Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist before requesting a review
- [x] I have followed the git practices outlined [here](GitPractices.md) to ensure code conflicts are minimized
- [x] My code follows the style guidelines of this project outlined [here](UIGuidelines.md)
- [x] I have performed a self-review of my code. It runs without errors and follows the [Best Coding Practices](BestCodingPractices.md)
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] There are no API keys, passwords, usernames, or other secrets in the code. .env files are used for these secrets.
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Manoj-kumar-surabhi** [comment]
New packages have been added to both dependencies and devDependencies and a new folder named "physical_fitness" has been created in the svr directory.

**Comment by jeffreywallphd** [comment]
Your tsx file belongs in the View folder, not the svr folder. Please move it to the View folder and update all links to it in App.jsx

**Comment by Manoj-kumar-surabhi** [comment]
The TSX file has been moved to the view directory, and the path in app.jsx has been updated accordingly. Please review it.

**Comment by jeffreywallphd** [comment]
Thanks @Manoj-kumar-surabhi . Please update your pull request template to answer all the required areas of explanation. You are missing the description and some other details. The review team uses that information to help them with the review.

**Comment by Manoj-kumar-surabhi** [comment]
Updated the pull request template.

**Comment by jeffreywallphd** [comment]
@Manoj-kumar-surabhi @kbaker49 gets busy with other project management tasks. In fairness to @kbaker49, could you please add some other reviewers from the core infrastructure team.

**Review by Divy0409 — APPROVED** [review]
Please don't forget to add your JIRA task or story number next time. Code  Your code is not having any issues. I am approving and merging your code.

**Pull request merged**
